### ISSUE TITLE
No sshd/settings.raw

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubports-pdk#1]
I'm not sure if I miss some steps. I did:
`setup` (on `../qemu`)
`pull`
reboot
`run`

but I get an error saying I have no settings.raw (which is true)

```
#####################################
Ubuntu Touch Platform Development Kit
#####################################

Executing tasks:
	Setup? no
	Clear cache? no
	List? no
	Pull image? no
	Create custom image? no
	Run an image? yes


Name of the environment: default

ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
qemu-system-x86_64: -drive if=virtio,format=raw,file=../qemu/sshd/settings.raw,readonly=on: Could not open '../qemu/sshd/settings.raw': No such file or directory
```

if I `create` it will complain saying:
[...]ubports-pdk/scripts/images.sh: línia 74: [...]/ubports-pdk/deps/rootfs-builder-debos/debos-docker:  file or folder doesn't exist`

Is it supposed to be set up under the main `ubports-pdk` directory and not outside?

**Comment by fredldotme** [comment]
Have you tried setting up the path in the `setup` step with an absolute path? I've not tried with a relative one, might be one reason it fails.

**Comment by fredldotme** [comment]
Also, create is not implemented properly, might hide it for now.

**Comment by cibersheep** [comment]
> Have you tried setting up the path in the `setup` step with an absolute path? I've not tried with a relative one, might be one reason it fails.

I have tested:
-creating a folder in the pdf folder
-using full route on setup and pull again (I don't think it's necessary but...)

I seem to be missing only the settings.raw under sshd/

![imatge](https://user-images.githubusercontent.com/6640041/123969146-3b7a1b00-d9b8-11eb-823c-d3292dc0e89d.png)

**Comment by fredldotme** [comment]
Hm, please paste the output of a re-attempted `setup` step (preferably with an absolute path)

**Comment by cibersheep** [comment]
```
#####################################
Ubuntu Touch Platform Development Kit
#####################################

Executing tasks:
	Setup? yes
	Clear cache? no
	List? no
	Pull image? no
	Create custom image? no
	Run an image? no

WARNING: You haven't set up your environment yet. Continuing with setup...
Installing prerequisites
No face model known
[sudo] contrasenya per a cibersheep: 
snap "qemu-ut-pdk" is already installed, see 'snap help refresh'
Set up KVM for cibersheep, logging out and back in is advised
Please enter the directory path you want to set up
Path: /home/cibersheep/Ubuntu-Touch-Projects/ubports-pdk/utfirst
$ 
```

**Comment by fredldotme** [comment]
It should print the following after the `Path` thing:

```
Inserting ssh key into authorized keys list
Generating image with settings
```

Is it opening a new shell? That `$` seems suspicious.

**Comment by cibersheep** [comment]
> Is it opening a new shell? That `$` seems suspicious.

Sorry... I just edit the user@device :)

It say nothing after typing the path.
Later tonight I'll test the changes

**Comment by fredldotme** [comment]
Which host OS are you using? I've tested the latest state with both macOS Big Sur and Ubuntu 20.04.

**Comment by just-carlod** [comment]
Hi I've got similar issue on Ubuntu 21.04, also I used absolute path in setup process

**Comment by just-carlod** [comment]
@fredldotme setup sub-command crashes at this line
https://github.com/ubports/ubports-pdk/blob/638dc3b7e77954cc2199449a1feb9d77af89fd33/scripts/setup.sh#L38
After removing it script ends with correct output

**Comment by fredldotme** [comment]
Very nice investigative work @just-carlod, it seems the OpenSSH service was renamed in the meantime.
Yeah, I'll remove the check and force the installation of OpenSSH unconditionally.

**Comment by fredldotme** [comment]
Or rather, could you possibly find out which service name corresponds to the ssh server now in newer versions?

**Comment by fredldotme** [comment]
Ok, I went ahead and added a second service name to probe for: https://github.com/ubports/ubports-pdk/tree/ubuntu-21.04

@cibersheep you might want to try that one too.

**Comment by just-carlod** [comment]
lol I was trying to update ssh and I realized that ssh is not preinstalled on 21.04 😂 script works fine, but I think it should detect that ssh is not preinstalled

**Comment by fredldotme** [comment]
Seems the script is failing to get the return code because I enabled `set -e`, which causes an exit on all non-zero returns of commands. I'd have to find a different way of querying whether sshd is enabled or not.

**Comment by cibersheep** [comment]
> Which host OS are you using? I've tested the latest state with both macOS Big Sur and Ubuntu 20.04.

Just for the record...
I'm on Ubuntu 20.04 (with Unity DE)

> Ok, I went ahead and added a second service name to probe for: https://github.com/ubports/ubports-pdk/tree/ubuntu-21.04

A-we-so-me 

With that brancj I get 
```
WARNING: The OpenSSH server seems to be missing or not activated, please install it using your package manager.
Would you like to do that automatically now [y/n]?
```

Which solves the issue. I can run it... yaaay!!
Thanks <3! 

Mayb I close the issue?

**Comment by fredldotme** [comment]
Merged, closed. Thanks for testing. :)
