### ISSUE TITLE
Mounting PDK source dir fails for snap

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-pdk#12]
Only for the snap version, mounting the PDK source dir fails.

```
# journalctl -u ubports-pdk-mount.service
-- Logs begin at Sun 2021-07-11 09:23:36 UTC, end at Sun 2021-07-11 09:27:16 UTC. --
Jul 11 09:23:39 linux systemd[1]: Starting Mount PDK host directory...
Jul 11 09:23:39 linux bash[512]: mount: /pdk/settings: WARNING: device write-protected, mounted read-only.
Jul 11 09:23:39 linux bash[505]: /pdk/settings still mounted
Jul 11 09:23:39 linux bash[520]: read: Connection reset by peer
Jul 11 09:23:39 linux systemd[1]: ubports-pdk-mount.service: Main process exited, code=exited, status=1/FAILURE
Jul 11 09:23:39 linux systemd[1]: ubports-pdk-mount.service: Failed with result 'exit-code'.
Jul 11 09:23:39 linux systemd[1]: Failed to start Mount PDK host directory.
```
Sources pulled as described in the README do not end up in the PDK environment directory therefore.

**Comment by fredldotme** [comment]
🤦I pushed the VM-side change to the wrong repo. Pushed now, should be available by 23:00 CEST time.
Requires a new image pull.

**Comment by fredldotme** [comment]
If you want to test the change locally, edit `/usr/libexec/ubports-pdk-mount` in the VM and make it look like this:

https://gitlab.com/ubports/core/rootfs-builder-debos/-/commit/bddf1bb04a1eebcb2195f56811ba785c7013e68c

**Comment by jonnius** [comment]
Yes. That solves it. :)
