### ISSUE TITLE
SDL display doesn't work on amd  GPUs

### ISSUE THREAD

**Issue by just-carlod** [ubports/ubports-pdk#2]
SDL display method doesn't work on my machine with ryzen 4500u and vega 6 iGPU. From my researches, this error may appear on more amd GPUs.

**Comment by just-carlod** [comment]
I made a pr with solution #3

**Comment by fredldotme** [comment]
Thanks, merged! If it turns out that the GTK display works better on Linux generally then we can make it the default later on.
