### ISSUE TITLE
set different number of trying when pulling

### ISSUE THREAD

**Issue by Aury88** [ubports/ubports-pdk#20]
I have very low bandwidth stability. 
Unfortunately when I did the pull I reached the twentieth attempt when I was at 96%, therefore it left the process when it was one step away from the end. 
is there any way to change the maximum number of pull attempts? 
is there a way to clone and store locally the development image as backup version so to avoid to have to pull again the image?

Used the snap version 0.0.0-rc0 2021-07-18 (143)

**Comment by fredldotme** [comment]
We could remove the download attempts attempts limit, sure, but what is more likely is that the server was refreshing the image and the PDK was trying to mix the old download with the new image in a new download attempt. This is a situation the PDK might not get out of and a sane default reaction needs to exist, hence keeping the download attempts at the wget default.

**Comment by fredldotme** [comment]
As long as we can't distinguish between actual failed attempts (due to packet loss) and the server exchanging an old image with a new one on its side (pulling the rug under your feet) raising the limit will not work.

There is the idea of importing an image though, yes, but someone needs to fully implement it.

**Comment by rapto** [comment]
If the image changes _that_ often, more than one attempt is useless. Some trivial versioning would be necessary. The link should be a redirect to the latest image.

**Comment by rapto** [comment]
The workaround is trivial, of course. Just clone the repo and add `-t0` to the wget invocation. I am trying that right now.

**Comment by fredldotme** [comment]
Images change every 24 hours. But no, more than one attempt is not useless (if they were then wget wouldn't have a default behavior), since Jenkins is known to have connectivity issues from time to time. The solution is to fix Jenkins.
