### ISSUE TITLE
Change license from 'none' to 'GPLv3'

### ISSUE THREAD

**Issue by fredldotme** [ubports/ubports-pdk#6]
We didn't have a license set up for this project before, so to make it easy and understandable what people are dealing with,
let's make this a GPLv3 licensed project.

Tagging existing contributors to ask for agreement to change the license to GPLv3:
- [x] @just-carlod 

Please agree or disagree to change the license below in a comment.

**Comment by just-carlod** [comment]
I agree :)

**Comment by fredldotme** [comment]
Thank you! :)
