### ISSUE TITLE
ubuntu-touch-pdk not in PATH after snap install

### ISSUE THREAD

**Issue by jonnius** [ubports/ubports-pdk#7]
I installed the PDK via `sudo snap install --edge ubports-pdk`. `ubuntu-touch-pdk` is not in `PATH` though. Interestingly there is `ubuntu-touch-pdk` in `PATH` (from `/snap/bin/ubports-pdk.pdk`). Running that seems to do the same as running the tool with from its absolute path `/snap/ubports-pdk/126/bin/ubuntu-touch-pdk`.

OS: Ubuntu 20.04

**Comment by fredldotme** [comment]
It's called `ubports-pdk.pdk` because we cannot ship a command with `ubuntu-` as a prefix, those are reserved for Canonical.
